### ISSUE TITLE
'github:hellwolf/solc.nix' does not provide attribute [...]

### ISSUE THREAD

**Issue by delehef** [hellwolf/solc.nix#14]
Hello,

It may very well be a case of me holding it's wrong, because your project works perfectly fine when called from a `flake.nix`; but when I tried to launch it in an ephemeral shell with `nix --extra-experimental-features nix-command --extra-experimental-features flakes shell github:hellwolf/solc.nix#solc_0_8_19`, I get: 

```
error: flake 'github:hellwolf/solc.nix' does not provide attribute 'packages.x86_64-linux.solc_0_8_19', 'legacyPackages.x86_64-linux.solc_0_8_19' or 'solc_0_8_19'
```

Nix 2.18.5, NixOS 24.05.

**Comment by hellwolf** [comment]
You are right, that command does not work anymore. I will fix it.

Thanks for the reporting!

**Comment by hellwolf** [comment]
Meanwhile, you could still use it as part of your own flake.

**Comment by hellwolf** [comment]
It should have been fixed!

**Comment by delehef** [comment]
Works like a charm, thanks a lot!
